package com.redhat.demos.cwtbookingdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CorporateProfile implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Corp Profile ID")
   private java.lang.String profileID;
   @org.kie.api.definition.type.Label("Corp Profile Name")
   private java.lang.String profileCorpName;
   @org.kie.api.definition.type.Label("Corp Profile Business Value Code")
   private java.lang.String profileCorpValueCode;
   @org.kie.api.definition.type.Label("Corp Profile Global Policy Codes")
   private java.util.List<java.lang.String> profileCorpPolicyCodes;

   public CorporateProfile()
   {
   }

   public java.lang.String getProfileID()
   {
      return this.profileID;
   }

   public void setProfileID(java.lang.String profileID)
   {
      this.profileID = profileID;
   }

   public java.lang.String getProfileCorpName()
   {
      return this.profileCorpName;
   }

   public void setProfileCorpName(java.lang.String profileCorpName)
   {
      this.profileCorpName = profileCorpName;
   }

   public java.lang.String getProfileCorpValueCode()
   {
      return this.profileCorpValueCode;
   }

   public void setProfileCorpValueCode(java.lang.String profileCorpValueCode)
   {
      this.profileCorpValueCode = profileCorpValueCode;
   }

   public java.util.List<java.lang.String> getProfileCorpPolicyCodes()
   {
      return this.profileCorpPolicyCodes;
   }

   public void setProfileCorpPolicyCodes(
         java.util.List<java.lang.String> profileCorpPolicyCodes)
   {
      this.profileCorpPolicyCodes = profileCorpPolicyCodes;
   }

   public CorporateProfile(java.lang.String profileID,
         java.lang.String profileCorpName,
         java.lang.String profileCorpValueCode,
         java.util.List<java.lang.String> profileCorpPolicyCodes)
   {
      this.profileID = profileID;
      this.profileCorpName = profileCorpName;
      this.profileCorpValueCode = profileCorpValueCode;
      this.profileCorpPolicyCodes = profileCorpPolicyCodes;
   }

}