package com.redhat.demos.cwtbookingdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TravelerProfile implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Traveler Profile ID")
   private java.lang.String travelerID;
   @org.kie.api.definition.type.Label("Corporate Profile")
   private com.redhat.demos.cwtbookingdemo.CorporateProfile corpProfile;

   @org.kie.api.definition.type.Label(value = "First Name")
   private java.lang.String firstName;

   @org.kie.api.definition.type.Label(value = "Family/Last Name")
   private java.lang.String surName;

   @org.kie.api.definition.type.Label(value = "Frequent Flyer/Loyalty Program ID")
   private java.util.List<java.lang.String> fqtTravelerProgamID;

   @org.kie.api.definition.type.Label(value = "Country of Residence")
   private java.lang.String residenceCountryCode;

   @org.kie.api.definition.type.Label(value = "Effective Date")
   private java.util.Date profileEffectiveDate;

   @org.kie.api.definition.type.Label(value = "Profile Active Indicator")
   private java.lang.Boolean profileActive;

   public TravelerProfile()
   {
   }

   public java.lang.String getTravelerID()
   {
      return this.travelerID;
   }

   public void setTravelerID(java.lang.String travelerID)
   {
      this.travelerID = travelerID;
   }

   public com.redhat.demos.cwtbookingdemo.CorporateProfile getCorpProfile()
   {
      return this.corpProfile;
   }

   public void setCorpProfile(
         com.redhat.demos.cwtbookingdemo.CorporateProfile corpProfile)
   {
      this.corpProfile = corpProfile;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getSurName()
   {
      return this.surName;
   }

   public void setSurName(java.lang.String surName)
   {
      this.surName = surName;
   }

   public java.util.List<java.lang.String> getFqtTravelerProgamID()
   {
      return this.fqtTravelerProgamID;
   }

   public void setFqtTravelerProgamID(
         java.util.List<java.lang.String> fqtTravelerProgamID)
   {
      this.fqtTravelerProgamID = fqtTravelerProgamID;
   }

   public java.lang.String getResidenceCountryCode()
   {
      return this.residenceCountryCode;
   }

   public void setResidenceCountryCode(java.lang.String residenceCountryCode)
   {
      this.residenceCountryCode = residenceCountryCode;
   }

   public java.util.Date getProfileEffectiveDate()
   {
      return this.profileEffectiveDate;
   }

   public void setProfileEffectiveDate(java.util.Date profileEffectiveDate)
   {
      this.profileEffectiveDate = profileEffectiveDate;
   }

   public java.lang.Boolean getProfileActive()
   {
      return this.profileActive;
   }

   public void setProfileActive(java.lang.Boolean profileActive)
   {
      this.profileActive = profileActive;
   }

   public TravelerProfile(java.lang.String travelerID,
         com.redhat.demos.cwtbookingdemo.CorporateProfile corpProfile,
         java.lang.String firstName, java.lang.String surName,
         java.util.List<java.lang.String> fqtTravelerProgamID,
         java.lang.String residenceCountryCode,
         java.util.Date profileEffectiveDate, java.lang.Boolean profileActive)
   {
      this.travelerID = travelerID;
      this.corpProfile = corpProfile;
      this.firstName = firstName;
      this.surName = surName;
      this.fqtTravelerProgamID = fqtTravelerProgamID;
      this.residenceCountryCode = residenceCountryCode;
      this.profileEffectiveDate = profileEffectiveDate;
      this.profileActive = profileActive;
   }

}