package redhat.airline;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CarInformation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Type of Car")
   private java.lang.String carType;

   public CarInformation()
   {
   }

   public java.lang.String getCarType()
   {
      return this.carType;
   }

   public void setCarType(java.lang.String carType)
   {
      this.carType = carType;
   }

   public CarInformation(java.lang.String carType)
   {
      this.carType = carType;
   }

}