package redhat.airline;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerInformation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Type of Customer")
   private java.lang.String customerType;

   public CustomerInformation()
   {
   }

   public java.lang.String getCustomerType()
   {
      return this.customerType;
   }

   public void setCustomerType(java.lang.String customerType)
   {
      this.customerType = customerType;
   }

   public CustomerInformation(java.lang.String customerType)
   {
      this.customerType = customerType;
   }

}