package redhat.airline;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class flightInformation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Payment Information")
   private redhat.airline.PaymentInformation paymentInfo;
   @org.kie.api.definition.type.Label("Seat Preference")
   private java.lang.String seatPreference;
   @org.kie.api.definition.type.Label("Meal Preference")
   private java.lang.String mealPreference;
   @org.kie.api.definition.type.Label("Date of Departure")
   private java.util.Date departureDate;
   @org.kie.api.definition.type.Label("Date of Return")
   private java.util.Date returnDate;
   @org.kie.api.definition.type.Label("Trip Reason")
   private java.lang.String tripReason;
   @org.kie.api.definition.type.Label("Comments")
   private java.lang.String comments;

   public flightInformation()
   {
   }

   public redhat.airline.PaymentInformation getPaymentInfo()
   {
      return this.paymentInfo;
   }

   public void setPaymentInfo(redhat.airline.PaymentInformation paymentInfo)
   {
      this.paymentInfo = paymentInfo;
   }

   public java.lang.String getSeatPreference()
   {
      return this.seatPreference;
   }

   public void setSeatPreference(java.lang.String seatPreference)
   {
      this.seatPreference = seatPreference;
   }

   public java.lang.String getMealPreference()
   {
      return this.mealPreference;
   }

   public void setMealPreference(java.lang.String mealPreference)
   {
      this.mealPreference = mealPreference;
   }

   public java.util.Date getDepartureDate()
   {
      return this.departureDate;
   }

   public void setDepartureDate(java.util.Date departureDate)
   {
      this.departureDate = departureDate;
   }

   public java.util.Date getReturnDate()
   {
      return this.returnDate;
   }

   public void setReturnDate(java.util.Date returnDate)
   {
      this.returnDate = returnDate;
   }

   public java.lang.String getTripReason()
   {
      return this.tripReason;
   }

   public void setTripReason(java.lang.String tripReason)
   {
      this.tripReason = tripReason;
   }

   public java.lang.String getComments()
   {
      return this.comments;
   }

   public void setComments(java.lang.String comments)
   {
      this.comments = comments;
   }

   public flightInformation(redhat.airline.PaymentInformation paymentInfo,
         java.lang.String seatPreference, java.lang.String mealPreference,
         java.util.Date departureDate, java.util.Date returnDate,
         java.lang.String tripReason, java.lang.String comments)
   {
      this.paymentInfo = paymentInfo;
      this.seatPreference = seatPreference;
      this.mealPreference = mealPreference;
      this.departureDate = departureDate;
      this.returnDate = returnDate;
      this.tripReason = tripReason;
      this.comments = comments;
   }

}