package redhat.airline;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HotelInformation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name of Hotel")
   private java.lang.String hotelName;

   public HotelInformation()
   {
   }

   public java.lang.String getHotelName()
   {
      return this.hotelName;
   }

   public void setHotelName(java.lang.String hotelName)
   {
      this.hotelName = hotelName;
   }

   public HotelInformation(java.lang.String hotelName)
   {
      this.hotelName = hotelName;
   }

}