package redhat.airline;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PassengerInformation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Passenger Name")
   private java.lang.String passengerName;
   @org.kie.api.definition.type.Label("Passenger Age")
   private int passengerAGe;
   @org.kie.api.definition.type.Label("Passenger Date of Birth")
   private java.util.Date passengarDOB;
   @org.kie.api.definition.type.Label("Address Line1")
   private java.lang.String address1;
   @org.kie.api.definition.type.Label("Address Line2")
   private java.lang.String address2;
   @org.kie.api.definition.type.Label("City")
   private java.lang.String city;
   @org.kie.api.definition.type.Label("State")
   private java.lang.String state;
   @org.kie.api.definition.type.Label("Zip")
   private java.lang.String zip;
   @org.kie.api.definition.type.Label("EmployeeOf")
   private java.lang.String employeeOf;

   public PassengerInformation()
   {
   }

   public java.lang.String getPassengerName()
   {
      return this.passengerName;
   }

   public void setPassengerName(java.lang.String passengerName)
   {
      this.passengerName = passengerName;
   }

   public int getPassengerAGe()
   {
      return this.passengerAGe;
   }

   public void setPassengerAGe(int passengerAGe)
   {
      this.passengerAGe = passengerAGe;
   }

   public java.util.Date getPassengarDOB()
   {
      return this.passengarDOB;
   }

   public void setPassengarDOB(java.util.Date passengarDOB)
   {
      this.passengarDOB = passengarDOB;
   }

   public java.lang.String getAddress1()
   {
      return this.address1;
   }

   public void setAddress1(java.lang.String address1)
   {
      this.address1 = address1;
   }

   public java.lang.String getAddress2()
   {
      return this.address2;
   }

   public void setAddress2(java.lang.String address2)
   {
      this.address2 = address2;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.String getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public java.lang.String getEmployeeOf()
   {
      return this.employeeOf;
   }

   public void setEmployeeOf(java.lang.String employeeOf)
   {
      this.employeeOf = employeeOf;
   }

   public PassengerInformation(java.lang.String passengerName, int passengerAGe,
         java.util.Date passengarDOB, java.lang.String address1,
         java.lang.String address2, java.lang.String city,
         java.lang.String state, java.lang.String zip,
         java.lang.String employeeOf)
   {
      this.passengerName = passengerName;
      this.passengerAGe = passengerAGe;
      this.passengarDOB = passengarDOB;
      this.address1 = address1;
      this.address2 = address2;
      this.city = city;
      this.state = state;
      this.zip = zip;
      this.employeeOf = employeeOf;
   }

}