package redhat.airline;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentInformation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "First Name on CC")
   private java.lang.String ccFirstName;
   @org.kie.api.definition.type.Label(value = "Last Name on CC")
   private java.lang.String ccLastName;
   @org.kie.api.definition.type.Label(value = "Credit Card Number")
   private int CCNumber;
   @org.kie.api.definition.type.Label(value = "CVV Number")
   private int cvv;
   @org.kie.api.definition.type.Label(value = "CC Expiration Month")
   private int expirationMonth;
   @org.kie.api.definition.type.Label(value = "CC Expiration Year")
   private int ccExpirationYear;

   public PaymentInformation()
   {
   }

   public java.lang.String getCcFirstName()
   {
      return this.ccFirstName;
   }

   public void setCcFirstName(java.lang.String ccFirstName)
   {
      this.ccFirstName = ccFirstName;
   }

   public java.lang.String getCcLastName()
   {
      return this.ccLastName;
   }

   public void setCcLastName(java.lang.String ccLastName)
   {
      this.ccLastName = ccLastName;
   }

   public int getCCNumber()
   {
      return this.CCNumber;
   }

   public void setCCNumber(int CCNumber)
   {
      this.CCNumber = CCNumber;
   }

   public int getCvv()
   {
      return this.cvv;
   }

   public void setCvv(int cvv)
   {
      this.cvv = cvv;
   }

   public int getExpirationMonth()
   {
      return this.expirationMonth;
   }

   public void setExpirationMonth(int expirationMonth)
   {
      this.expirationMonth = expirationMonth;
   }

   public int getCcExpirationYear()
   {
      return this.ccExpirationYear;
   }

   public void setCcExpirationYear(int ccExpirationYear)
   {
      this.ccExpirationYear = ccExpirationYear;
   }

   public PaymentInformation(java.lang.String ccFirstName,
         java.lang.String ccLastName, int CCNumber, int cvv,
         int expirationMonth, int ccExpirationYear)
   {
      this.ccFirstName = ccFirstName;
      this.ccLastName = ccLastName;
      this.CCNumber = CCNumber;
      this.cvv = cvv;
      this.expirationMonth = expirationMonth;
      this.ccExpirationYear = ccExpirationYear;
   }

}