package redhat.airline;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TripInformation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Trip ID")
   private java.lang.String tripid;

   @org.kie.api.definition.type.Label("Type of Trip")
   private java.lang.String triptype;

   @org.kie.api.definition.type.Label(value = "Car Information")
   private redhat.airline.CarInformation carinfo;

   @org.kie.api.definition.type.Label(value = "Hotel Information")
   private redhat.airline.HotelInformation hotelInfo;

   @org.kie.api.definition.type.Label(value = "Flight information")
   private redhat.airline.flightInformation flightinfo;

   public TripInformation()
   {
   }

   public java.lang.String getTripid()
   {
      return this.tripid;
   }

   public void setTripid(java.lang.String tripid)
   {
      this.tripid = tripid;
   }

   public java.lang.String getTriptype()
   {
      return this.triptype;
   }

   public void setTriptype(java.lang.String triptype)
   {
      this.triptype = triptype;
   }

   public redhat.airline.CarInformation getCarinfo()
   {
      return this.carinfo;
   }

   public void setCarinfo(redhat.airline.CarInformation carinfo)
   {
      this.carinfo = carinfo;
   }

   public redhat.airline.HotelInformation getHotelInfo()
   {
      return this.hotelInfo;
   }

   public void setHotelInfo(redhat.airline.HotelInformation hotelInfo)
   {
      this.hotelInfo = hotelInfo;
   }

   public redhat.airline.flightInformation getFlightinfo()
   {
      return this.flightinfo;
   }

   public void setFlightinfo(redhat.airline.flightInformation flightinfo)
   {
      this.flightinfo = flightinfo;
   }

   public TripInformation(java.lang.String tripid, java.lang.String triptype,
         redhat.airline.CarInformation carinfo,
         redhat.airline.HotelInformation hotelInfo,
         redhat.airline.flightInformation flightinfo)
   {
      this.tripid = tripid;
      this.triptype = triptype;
      this.carinfo = carinfo;
      this.hotelInfo = hotelInfo;
      this.flightinfo = flightinfo;
   }

}